name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore src/Wootrade/Wootrade.sln
    - name: Build
      run: dotnet build --no-restore -c Release src/Wootrade/Wootrade.sln
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal src/Wootrade/Wootrade.sln
