name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      
    - name: Pack Wootrade
      run: dotnet pack src/Wootrade/Wootrade.csproj -c Release --include-symbols /p:Version=${{ github.event.release.tag_name }}
          
    - name: Publish
      run: dotnet nuget push ./**/*.nupkg -k ${{ secrets.NUGET_PUBLISH_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Print Version
      run: echo ${{ github.event.release.tag_name }}
