name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/WOOTRADE_ISSUES.md'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      WOO_TESTS_API_KEY: ${{ secrets.WOO_TESTS_API_KEY }}
      WOO_TESTS_API_SECRET: ${{ secrets.WOO_TESTS_API_SECRET }}
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore src/Wootrade.sln
    - name: Build
      run: dotnet build --no-restore -c Release src/Wootrade.sln
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal src/Wootrade.sln
